; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	C:\Code\CSCI247\Code\C_Examples\03ReadWriteLocalStackVariables\Program.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_y$ = -12						; size = 4
_x$ = -8						; size = 4
_sum$ = -4						; size = 4
_main	PROC
; File C:\Code\CSCI247\Code\C_Examples\03ReadWriteLocalStackVariables\Program.c
; Line 2
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 3
	mov	DWORD PTR _x$[ebp], 1
; Line 4
	mov	DWORD PTR _y$[ebp], 2
; Line 5
	mov	DWORD PTR _sum$[ebp], 0
; Line 7
	mov	eax, DWORD PTR _x$[ebp]
	add	eax, DWORD PTR _y$[ebp]
	mov	DWORD PTR _sum$[ebp], eax
; Line 9
	mov	eax, DWORD PTR _sum$[ebp]
; Line 10
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
