; Listing generated by Microsoft (R) Optimizing Compiler Version 19.27.29111.0 

	TITLE	C:\Code\CSCI247\Code\C_Examples\06Procedures\01SingleFile\Program.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_sum
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -12						; size = 4
_x$ = -8						; size = 4
_y$ = -4						; size = 4
_main	PROC
; File C:\Code\CSCI247\Code\C_Examples\06Procedures\01SingleFile\Program.c
; Line 11
	push	ebp
	mov	ebp, esp
	sub	esp, 12					; 0000000cH
; Line 12
	mov	DWORD PTR _x$[ebp], 1
; Line 13
	mov	DWORD PTR _y$[ebp], 2
; Line 15
	mov	eax, DWORD PTR _y$[ebp]
	push	eax
	mov	ecx, DWORD PTR _x$[ebp]
	push	ecx
	call	_sum
	add	esp, 8
	mov	DWORD PTR _result$[ebp], eax
; Line 17
	mov	eax, DWORD PTR _result$[ebp]
; Line 18
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -4						; size = 4
_x$ = 8							; size = 4
_y$ = 12						; size = 4
_sum	PROC
; File C:\Code\CSCI247\Code\C_Examples\06Procedures\01SingleFile\Program.c
; Line 2
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 3
	mov	DWORD PTR _result$[ebp], 0
; Line 5
	mov	eax, DWORD PTR _x$[ebp]
	add	eax, DWORD PTR _y$[ebp]
	mov	DWORD PTR _result$[ebp], eax
; Line 7
	mov	eax, DWORD PTR _result$[ebp]
; Line 8
	mov	esp, ebp
	pop	ebp
	ret	0
_sum	ENDP
_TEXT	ENDS
END
